version: "3.9"

volumes:
  postgres_data_owners:
  postgres_data_cats:
  postgres_data_user_details:

name: lab5

services:
  postgres_cat_owner:
    container_name: cat-owner
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data_owners:/var/lib/postgresql/data
    ports:
      - "${OWNER_SERVICE_DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}


  postgres_cat:
    container_name: cats
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data_cats:/var/lib/postgresql/data
    ports:
      - "${CAT_SERVICE_DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}


  postgres_user_details:
    container_name: user
    image: postgres:latest
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres_data_user_details:/var/lib/postgresql/data
    ports:
      - "${USER_DETAILS_DB_PORT}:${DB_PORT}"
    environment:
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}


  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1